---
- name: Deploy MySQL Database
  command: "oc new-app --template=mysql-ephemeral --param=MYSQL_PASSWORD=password --param=MYSQL_USER=dbuser --param=MYSQL_DATABASE=sampledb -n {{ project }}"

- name: Deploy PostgreSQL Database
  command: "oc new-app --template=postgresql-ephemeral --param=POSTGRESQL_USER=dbuser --param=POSTGRESQL_PASSWORD=password --param=POSTGRESQL_DATABASE=sampledb -n {{ project }}"

- name: Wait for databases to be ready
  command: "oc wait --for=condition=Ready pods --selector {{item}}  -n {{project}}"
  loop:
    - name=mysql
    - name=postgresql

- name: Get mysql pod
  command: "oc get pod -l app=mysql-ephemeral -o jsonpath='{.items[0].metadata.name}'"
  register: mysql-pod

- name: Upload mysql schema
  command: "oc rsync ../files/db-mysql {{ mysql-pod }}:/var/lib/mysql/data"

- name: Create mysql schema
  command: "oc exec {{ mysql-pod}} -- bash -c 'mysql --user=dbuser --password=password sampledb < /var/lib/mysql/data/db-mysql/schema.sql'"

- name: Get postgreSQL pod
  command: "oc get pod -l app=postgresql-ephemeral -o jsonpath='{.items[0].metadata.name}'"
  register: pssql-pod

- name: Upload postgresql schema
  command: "oc rsync ../files/db-psql {{ psql-pod }}:/var/lib/pgsql/data/userdata"

- name: Create mysql schema
  command: "oc exec {{ psql-pod }} -- bash -c 'psql -U dbuser -d sampledb -a -f /var/lib/pgsql/data/userdata/db-psql/schema.sql'"
