---
- name: Debug app
  debug:
    msg: " Deploying {{ app.name }}"

- name: "Create build {{ app.name }}"
  command: "oc new-build {{ app.image }}:{{ app.version }}~{{ git_repo }} --name={{ app.name }} --context-dir={{ app.name }} -n {{ project }}"
  when: app.image is defined

- name: "Create application {{ app.name }}"
  shell: "oc process -f {{ role_path }}/files/{{ app.template }}.yml -p GIT_REPO={{ git_repo }} -p GIT_CONTEXT_DIR={{ app.name }} -p APP_NAME={{ app.name }} | oc create -f -"
  when: app.template is defined

- name: Wait for build to be started
  pause:
    seconds: 1

- name: "Wait for build {{ app.name }}"
  command: "oc logs bc/{{ app.name }} --follow"
  no_log: true

- name: "Deploy {{ app.name }}"
  command: "oc new-app --name={{ app.name }} --image-stream={{ app.name }} -n {{ project }}"
  when: app.image is defined

- name: Wait for artifacts to be created
  pause:
    seconds: 1

# - name: Add routeui configuration map
#   command: "oc set env --from=cm/uirouteconfig dc/{{ app.name }}"
#   when: app.image == "nodejs"

# Skip waiting here to improve performance
# - name: "Wait for {{ app.name }} to be ready"
#   command: "oc wait --for=condition=Ready pods --selector name={{app.name}}  -n {{project}}"

- name: "Create route for {{ app.name }}"
  command: "oc expose svc/{{ app.name }} --port=8080"
  when: app.expose and app.image is defined