---
- name: Debug app
  debug:
    msg: "{{ app }}"

- name: "Create Build {{ app.name }}"
  command: "oc new-build {{ app.image }}:{{ app.version }}~{{ git_repo }} --name={{ app.name }} --context-dir={{ app.name }} -n {{ project }}"

- name: Wait for build to be started
  pause:
    seconds: 1

- name: "Wait for build {{ app.name }}"
  command: "oc logs bc/{{ app.name }} --follow"
  no_log: true

- name: "Deploy {{ app.name }}"
  command: "oc new-app {{ app.name }} -n {{ project }}"

- name: Wait for artifacts to be created
  pause:
    seconds: 1

# - name: Add routeui configuration map
#   command: "oc set env --from=cm/uirouteconfig dc/{{ app.name }}"
#   when: app.image == "nodejs"

# Skip waiting here to improve performance
# - name: "Wait for {{ app.name }} to be ready"
#   command: "oc wait --for=condition=Ready pods --selector name={{app.name}}  -n {{project}}"

- name: "Create route for {{ app.name }}"
  command: "oc expose svc/{{ app.name }} --port=8080"
  when: app.expose