---
- name: Deploy Applications
  include: add-user.yml app={{ item }}
  loop:
    - {name: transform-camel, image: fuse7-java-openshift, version: 1.2, expose: false}
    - {name: seat-ui-listener, image: fuse7-java-openshift, version: 1.2, expose: false}
    - {name: seat-ui-reader, image: fuse7-java-openshift, version: 1.2, expose: false}
    - {name: registration-ui, image: fuse7-eap-openshift, version: 1.2, expose: false}
    - {name: seat-reserve-simulator, image: fuse7-eap-openshift, version: 1.2, expose: false}
    - {name: registration-command, image: fuse7-java-openshift, version: 1.2, expose: false}
    - {name: analytic-listener, image: fuse7-java-openshift, version: 1.2, expose: false}
    - {name: analytic-ui, image: nodejs, version: 8, expose: true}
    - {name: seat-ui, image: nodejs, version: 8, expose: true}
    - {name: registration-live-ui, image: nodejs, version: 8, expose: true}