---
- name: Debug template
  template:
    src: ./templates/streams.j2
    dest: /home/gnunn/streams.yaml

- name: Deploy AMQ Streams
  k8s:
    state: present
    namespace: "{{ project }}"
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - ./templates/streams.j2

- name: Wait for streams
  debug:
    msg: "Please wait for Kafka to be ready, this may take several minutes"

- name: Pause 1 minute
  pause:
    minutes: 1

- name: Wait for AMQ Streams operator pod
  command: "oc wait --for=condition=Ready pods --selector amq-streams-cluster-operator -n {{project}} --timeout=300s"

- name: Pause 1 minute
  pause:
    minutes: 1

- name: Wait for Kafka to be ready
  command: "oc wait --for=condition=Ready pods --selector strimzi.io/cluster=sko  -n {{project}} --timeout=300s"