---
- name: Deploy AMQ Streams
  k8s:
    state: present
    namespace: "{{ project }}"
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - ./templates/streams-persistent.j2

- debug:
    msg: "Please wait for Kafka to be ready, this may take several minutes"

- pause:
    minutes: 1

- name: Wait for AMQ Streams operator pod
  command: "oc wait --for=condition=Ready pods --selector amq-streams-cluster-operator -n {{project}}"

- pause:
    minutes: 1

- name: Wait for Kafka to be ready
  command: "oc wait --for=condition=Ready pods --selector strimzi.io/cluster=sko  -n {{project}}"