---
apiVersion: v1
kind: Template
metadata:
  annotations:
    openshift.io/display-name: Camel Spring Boot REST Template
    openshift.io/provider-display-name: Gerald Nunn
    description: Spring Boot and Camel template with port 8080 exposed for web services, based on s2i-fuse72-spring-boot-cxf-jaxrs template
    tags: java,springboot,fis,jboss-fuse
    iconClass: icon-rh-integration
    version: '1.2'
  name: s2i-fuse-spring-boot-rest
labels:
  template: s2i-fuse-spring-boot-rest
parameters:
- name: APP_NAME
  displayName: Application Name
  required: true
  value:
  description: The name assigned to the application.
- name: GIT_REPO
  displayName: Git Repository URL
  required: true
  value:
  description: The URL of the repository with your application source code.
- name: GIT_REF
  displayName: Git Reference
  value: master
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
- name: GIT_CONTEXT_DIR
  displayName: Git Context Dir
  value:
- name: BUILDER_VERSION
  displayName: Builder version
  value: '1.2'
  description: The version of the FIS S2I builder image to use.
- name: APP_VERSION
  displayName: Application Version
  value:
  description: The application version.
- name: MAVEN_ARGS
  displayName: Maven Arguments
  value: package -DskipTests -Dfabric8.skip -e -B
  description: Arguments passed to mvn in the build.
- name: MAVEN_ARGS_APPEND
  displayName: Extra Maven Arguments
  description: Extra arguments passed to mvn, e.g. for multi-module builds.
- name: ARTIFACT_DIR
  displayName: Maven build directory
  description: Directory of the artifact to be built, e.g. for multi-module builds.
- name: IMAGE_STREAM_NAMESPACE
  displayName: Image Stream Namespace
  value: openshift
  required: true
  description: Namespace in which the Fuse ImageStreams are installed. These ImageStreams
    are normally installed in the openshift namespace. You should only need to modify
    this if you've installed the ImageStreams in a different namespace/project.
- name: BUILD_SECRET
  displayName: Git Build Secret
  generate: expression
  description: The secret needed to trigger a build.
  from: "[a-zA-Z0-9]{40}"
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      component: "${APP_NAME}"
      provider: s2i
      app: "${APP_NAME}"
      version: "${APP_VERSION}"
    name: "${APP_NAME}"
  spec:
    to:
      kind: Service
      name: "${APP_NAME}"
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      component: "${APP_NAME}"
      provider: s2i
      app: "${APP_NAME}"
      version: "${APP_VERSION}"
    name: "${APP_NAME}"
  spec:
    clusterIP: None
    deprecatedPublicIPs: []
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: web
    - name: metric
      port: 9779
    selector:
      app: "${APP_NAME}"
      component: "${APP_NAME}"
      provider: s2i
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp:
    labels:
      component: "${APP_NAME}"
      app: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
  spec: {}
  status:
    dockerImageRepository: ''
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp:
    labels:
      component: "${APP_NAME}"
      app: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
  spec:
    triggers:
    - type: GitHub
      github:
        secret: "${BUILD_SECRET}"
    - type: Generic
      generic:
        secret: "${BUILD_SECRET}"
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    source:
      type: Git
      contextDir: ${GIT_CONTEXT_DIR}
      git:
        uri: "${GIT_REPO}"
        ref: "${GIT_REF}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_STREAM_NAMESPACE}"
          name: fuse7-java-openshift:${BUILDER_VERSION}
        forcePull: true
        incremental: true
        env:
        - name: BUILD_LOGLEVEL
          value: '5'
        - name: ARTIFACT_DIR
          value: "${ARTIFACT_DIR}"
        - name: MAVEN_ARGS
          value: "${MAVEN_ARGS}"
        - name: MAVEN_ARGS_APPEND
          value: "${MAVEN_ARGS_APPEND}"
    output:
      to:
        kind: ImageStreamTag
        name: "${APP_NAME}:latest"
  status:
    lastVersion: 0
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    creationTimestamp:
    labels:
      component: "${APP_NAME}"
      app: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${APP_NAME}"
        from:
          kind: ImageStreamTag
          name: "${APP_NAME}:latest"
    replicas: 1
    selector:
      component: "${APP_NAME}"
      deploymentconfig: "${APP_NAME}"
      app: "${APP_NAME}"
      provider: s2i
      version: "${APP_VERSION}"
    template:
      metadata:
        creationTimestamp:
        labels:
          component: "${APP_NAME}"
          deploymentconfig: "${APP_NAME}"
          app: "${APP_NAME}"
          provider: s2i
          version: "${APP_VERSION}"
          metrics: camel
      spec:
        containers:
        - name: "${APP_NAME}"
          image: library/${APP_NAME}:latest
          ports:
          - containerPort: 8778
            name: jolokia
          env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace